[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/whatsapp"
  to = "https://wa.me/256701673510?text=Hi%20POP%20team,%20I'd%20like%20to%20get%20in%20touch!"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"